CREATE TABLE guilds (
    guild_id TEXT PRIMARY KEY,
    joined_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE guilds ENABLE ROW LEVEL SECURITY;

CREATE POLICY "deny_all"
ON guilds
FOR ALL
USING (FALSE)
WITH CHECK (FALSE);